# Generated by Django 6.0.4 on 2026-04-14 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Movie",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("synopsis", models.TextField(blank=True)),
                ("genre", models.CharField(blank=True, max_length=100)),
                ("cast", models.TextField(blank=True)),
                ("release_year", models.IntegerField(blank=True, null=True)),
                ("language", models.CharField(blank=True, max_length=50)),
                ("poster_url", models.URLField(blank=True)),
            ],
        ),
    ]
